// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6vOvwPqrhP27jLuxsFCWuDAHD4Hsl6ec',
    appId: '1:97441375090:web:7c80a4856e1fcb4fdc33eb',
    messagingSenderId: '97441375090',
    projectId: 'housecarmaintenance',
    authDomain: 'housecarmaintenance.firebaseapp.com',
    storageBucket: 'housecarmaintenance.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApuLST2Rl4zZgwmEBOHY0VgvGGQG5navw',
    appId: '1:97441375090:android:4fac37eeba4f56c5dc33eb',
    messagingSenderId: '97441375090',
    projectId: 'housecarmaintenance',
    storageBucket: 'housecarmaintenance.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuyqjS_eOD8LZ6CHfcmyfzG8iQeclY1AI',
    appId: '1:97441375090:ios:7095346dd546dfc5dc33eb',
    messagingSenderId: '97441375090',
    projectId: 'housecarmaintenance',
    storageBucket: 'housecarmaintenance.appspot.com',
    iosBundleId: 'com.example.izProperties',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuyqjS_eOD8LZ6CHfcmyfzG8iQeclY1AI',
    appId: '1:97441375090:ios:b1ccc225757f7b71dc33eb',
    messagingSenderId: '97441375090',
    projectId: 'housecarmaintenance',
    storageBucket: 'housecarmaintenance.appspot.com',
    iosBundleId: 'com.example.izProperties.RunnerTests',
  );
}
